import java.awt.Color;
import java.awt.Component;
import java.awt.event.ActionListener;
import java.io.File;

import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Coco
 */
public class VentanaInicio extends javax.swing.JDialog {

    /**
     * Creates new form VentanaInicio
     */
	
	
    public VentanaInicio(java.awt.Frame parent, boolean modal) {
          	
    	super(parent, modal);

        //Inicio.servicios = Inicio.excel.listaServicios;
        initComponents();
    }

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
    	
    	if(Inicio.documentacion == 1){
    		setTitle("Documentación");
    	}else if(Inicio.documentacion == 0){
    		setTitle("Urgencias");
    	}else if(Inicio.documentacion == 2){
    		setTitle("Salnés Documentación");
    	}else if(Inicio.documentacion == 3){
    		setTitle("Salnés Urgencias");
    	}
     	
        jSeparator2 = new javax.swing.JSeparator();
        jlistaUsuarios = new javax.swing.JComboBox();
        jEtiquetaNombres = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        jBotonNUsuario = new javax.swing.JButton();
        jEtiquetaNUsuario = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jBoton1Ianus = new javax.swing.JButton();
        jBoton2Ianus = new javax.swing.JButton();
        jEtiquetaIanus = new javax.swing.JLabel();
        
        
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
 

        
                
        jlistaUsuarios.setBackground(new java.awt.Color(255, 204, 204));
        jlistaUsuarios.setMaximumRowCount(7);
        if(Inicio.documentacion == 1 || Inicio.documentacion == 2){
            jlistaUsuarios.setModel(Inicio.excel.listaUsuarios);
            Inicio.RUTASAL = Inicio.detectaUnidadSalnes() + Inicio.RUTASAL_DOC;
            Inicio.RUTAMENSAJES_DOC = Inicio.detectaUnidadSalnes() + Inicio.RUTAMENSAJES_DOC;
        }else{
        	jlistaUsuarios.setModel(Inicio.excel.listaUsuariosUrg);
        	Inicio.RUTASAL = Inicio.detectaUnidadSalnes() + Inicio.RUTASAL_URG;
        	Inicio.RUTAMENSAJES_URG = Inicio.detectaUnidadSalnes() + Inicio.RUTAMENSAJES_URG;
        }

        jlistaUsuarios.setSelectedIndex(0);
        jlistaUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Inicio.usuario = jlistaUsuarios.getSelectedItem().toString();
            	jPanel2.setVisible(true);
            }
        });

        jEtiquetaNombres.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEtiquetaNombres.setText("Selecciona Usuario");

        jPanel1.setBackground(new java.awt.Color(253, 221, 225));
        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        

        jBotonNUsuario.setText("Introducir");
        /*
        jBotonNUsuario.addActionListener(new ActionListener(){
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	Inicio.usuario = JOptionPane.showInputDialog(jPanel1, "Escribe tu nombre", "", JOptionPane.QUESTION_MESSAGE);
            	if(InicioIanus.usuario != null){
            		boolean repetido = false;
            		for(int i=0;i<jlistaUsuarios.getItemCount();i++){
            			if( jlistaUsuarios.getItemAt(i).toString().toLowerCase().contains(InicioIanus.usuario.toLowerCase())){
            				JOptionPane.showMessageDialog(null, "Usuario ya en uso");
            				jlistaUsuarios.setSelectedIndex(i);
            				repetido = true;
            				break;
            			}
            		}
            		if(!repetido){
            			InicioIanus.excel.listaUsuarios.addElement(InicioIanus.usuario);
            			jlistaUsuarios.setModel(InicioIanus.excel.listaUsuarios);
            			jlistaUsuarios.setSelectedIndex(jlistaUsuarios.getItemCount()-1);
            		}
            		jPanel1.setVisible(false);
            	}
            }       	
        });
         */
        
        jEtiquetaNUsuario.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEtiquetaNUsuario.setText("Nuevo Usuario");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jBotonNUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 21, Short.MAX_VALUE)
                        .addComponent(jEtiquetaNUsuario, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(20, 20, 20))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEtiquetaNUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jBotonNUsuario)
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 204));
        jPanel2.setBorder(javax.swing.BorderFactory.createEtchedBorder());


        
        jBoton1Ianus.setText("Aceptar");
        jBoton1Ianus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	System.out.println("El usuario es... " + Inicio.usuario );
            	dispose();
            }
        });
        
        jBoton2Ianus.setVisible(false);
        /*
        jBoton2Ianus.setText("2 Ianus");
        if(InicioIanus.documentacion == 2){
        	jBoton2Ianus.setEnabled(false);
        }
        jBoton2Ianus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBotonIanusActionPerformed(evt);
            }
        });

        jEtiquetaIanus.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jEtiquetaIanus.setText("¿Cuántos Ianus vas a utilizar?");
         */
        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jBoton1Ianus, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addComponent(jBoton2Ianus, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jEtiquetaIanus))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jEtiquetaIanus)
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBoton1Ianus)
                    .addComponent(jBoton2Ianus))
                .addGap(34, 34, 34))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jEtiquetaNombres)
                            .addComponent(jlistaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 5, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jEtiquetaNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlistaUsuarios, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
        super.setLocationRelativeTo(null);	//	Colocar siempre después de un pack(), o un setVisible()
        super.setResizable(false);
        jPanel2.setVisible(false);
        
    }// </editor-fold>//GEN-END:initComponents

    /*
    private void jBotonIanusActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    	if(evt.getSource() == jBoton1Ianus){
    			//InicioIanus.tandaDePdfs = new File[1];
    			//InicioIanus.numeroIanus = 1;
    	        InicioIanus.coordenadasIanus = new int[12][3];
    	        InicioIanus.coordenadasIanus = InicioIanus.excel.getCoordenadasIanus(12);
    	}
    	else if(evt.getSource() == jBoton2Ianus){
    			InicioIanus.tandaDePdfs = new File[2];
				InicioIanus.numeroIanus = 2;
		        InicioIanus.coordenadasIanus = new int[12][3];
		        InicioIanus.coordenadasIanus = InicioIanus.excel.getCoordenadasIanus(12);
				
				int opcion = JOptionPane.showOptionDialog(null, "¿Los 2 ianus en la misma pantalla?", "Colocación de los ianus", 
							JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE,null, new Object[] {"Si","No"}, "Si");

				if(opcion == 1){  	// Un ianus en cada pantalla
						InicioIanus.ianus2pantallas = true;
				}
				else{				// Dos ianus en la misma pantalla
					InicioIanus.ianus2pantallas = false;
				}
    	}
    	super.dispose();
    }
    
    */
    /**
     * @param args the command line arguments
     */
 
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBoton1Ianus;
    private javax.swing.JButton jBoton2Ianus;
    private javax.swing.JButton jBotonNUsuario;
    private javax.swing.JLabel jEtiquetaIanus;
    private javax.swing.JLabel jEtiquetaNUsuario;
    private javax.swing.JLabel jEtiquetaNombres;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JComboBox jlistaUsuarios;
    // End of variables declaration//GEN-END:variables
}
