import java.awt.Color;
import java.awt.Dimension;
import java.awt.MouseInfo;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.awt.event.MouseMotionListener;

import javax.swing.JButton;
import javax.swing.JLabel;


public class VentanaFechas extends javax.swing.JDialog {

	private java.awt.Point coordenadasRaton = new java.awt.Point();
	
    private JButton jBhoy0;
	private JLabel jLhoy0;
	/**
     * Creates new form VentanaFechas
     */
    public VentanaFechas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLfechaRegistrada = new javax.swing.JLabel();
        jBEnter = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jBhoy3 = new javax.swing.JButton();
        jBhoy2 = new javax.swing.JButton();
        jBhoy1 = new javax.swing.JButton();
        jBhoy0 = new javax.swing.JButton();
        jLhoy3 = new javax.swing.JLabel();
        jLhoy2 = new javax.swing.JLabel();
        jLhoy1 = new javax.swing.JLabel();
        jLhoy0 = new javax.swing.JLabel();
        jBpersonal = new javax.swing.JButton();
        jLpersonal = new javax.swing.JLabel();

      //  setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        
        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setMaximumSize(new java.awt.Dimension(20, 200));
        jPanel2.setMinimumSize(new java.awt.Dimension(20, 100));
        jPanel2.setPreferredSize(new java.awt.Dimension(20, 100));
        jPanel2.setRequestFocusEnabled(false);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 35, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

       // jPanel3.setBackground(new java.awt.Color(102, 0, 0));

        jPanel3.setBackground(new Color(255,229,204));
        
        jTextField1.setText("");
        jTextField1.setSize(0,6);
        jTextField1.setEditable(false);
        jTextField1.setFocusable(false);
        jTextField1.setFont(new java.awt.Font("Times", 1, 22)); // NOI18N
        
        jLfechaRegistrada.setFont(new java.awt.Font("Times", 1, 58)); // NOI18N
        jLfechaRegistrada.setForeground(Color.BLACK);
        jLfechaRegistrada.setText("");

        jBEnter.setText("Aceptar");
               
        jTextField1.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				System.out.println("Tecleando");
			}
		});
        
        jBEnter.addActionListener(new ActionListener() {
			
			@Override
			public void actionPerformed(ActionEvent e) {
				// TODO Auto-generated method stub
				
				Inicio.utiles.registraFecha();
				setVisible(false);
			}
		});

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLfechaRegistrada, javax.swing.GroupLayout.DEFAULT_SIZE, 118, Short.MAX_VALUE)
                .addGap(45, 45, 45)
             //   .addComponent(jBEnter, 50, 50, 50)
                .addGap(19, 19, 19))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
  //              .addGap(19, 19, 19)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLfechaRegistrada)
             //       .addComponent(jBEnter,50,50,50)
                    )
  //              .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        ));

        jPanel4.setBackground(new java.awt.Color(255, 204, 204));

        jBhoy3.setText("HOY -3");
        jBhoy3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                actualizarFecha(evt);
                
            }
        });

        jBhoy2.setText("HOY -2");
        jBhoy2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actualizarFecha(evt);
            }
        });

        jBhoy1.setText("AYER");
        jBhoy1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actualizarFecha(evt);
            }
        });

        jBhoy0.setText("HOY");
        jBhoy0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actualizarFecha(evt);
            }
        });
        
        jLhoy3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLhoy3.setText("10/01/15");

        jLhoy2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLhoy2.setText("09/01/15");

        jLhoy1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLhoy1.setText("08/01/15");
        
        jLhoy0.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLhoy0.setText("08/01/15");

        jBpersonal.setText("Personal");
        jBpersonal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
            	actualizarFecha(evt);
            }
        });

        jLpersonal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLpersonal.setText("08/01/15");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jBhoy3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLhoy3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBhoy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLhoy2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBhoy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLhoy1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBhoy0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLhoy0, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBpersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLpersonal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20)
                .addComponent(jBEnter,100,100,100)
                .addGap(20, 20, 20))
            
                
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jBhoy3)
                            .addComponent(jBhoy2)
                            .addComponent(jBhoy1)
                            .addComponent(jBhoy0)
                            .addComponent(jBpersonal))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLhoy3)
                            .addComponent(jLhoy2)
                            .addComponent(jLhoy1)
                            .addComponent(jLhoy0)
                            .addComponent(jLpersonal))))
              //  .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                           
            		)
            		.addComponent(jBEnter,55,55,55)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(0, 0, 0))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
  //              .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        
		jPanel2.addMouseListener(new MouseListener() {
			
			@Override
			public void mouseReleased(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mousePressed(MouseEvent e) {
				// TODO Auto-generated method stub
				if(e.getComponent() == jPanel2){
					coordenadasRaton = e.getPoint();
					System.out.println("Pinche en el panel");
				}
			}
			
			@Override
			public void mouseExited(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseEntered(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
			
			@Override
			public void mouseClicked(MouseEvent e) {
				// TODO Auto-generated method stub
				
			}
		});
		
		jPanel2.addMouseMotionListener(new MouseMotionListener() {

			@Override
			public void mouseMoved(MouseEvent e) {
				// TODO Auto-generated method stub

			}

			@Override
			public void mouseDragged(MouseEvent e) {
				// TODO Auto-generated method stub
				java.awt.Point punto = MouseInfo.getPointerInfo().getLocation();
				setLocation(punto.x - coordenadasRaton.x, punto.y
						- coordenadasRaton.y);
			}
		});
        
        setUndecorated(true);
        pack();
        
        setSize(new Dimension(660,150));
        
        reseteaColorBotones();
        actualizarFechas();
     //   setModal(false);
        
    }// </editor-fold>                        

    private void actualizarFechas(){
    	
        Fechas fechas = new Fechas();
        jLfechaRegistrada.setText(fechas.fechaHoy);
    	
    	jLhoy0.setText(fechas.fechaHoy);
    	jBhoy0.setBackground(Color.green);
    	
    	jBhoy1.setText(fechas.diaAyer);
    	jLhoy1.setText(fechas.fechaAyer);
    	
    	jBhoy2.setText(fechas.diaAnteayer);
    	jLhoy2.setText(fechas.fechaAnteayer);
    	
    	jBhoy3.setText(fechas.diaAnteAnteayer);
    	jLhoy3.setText(fechas.fechaAnteAnteayer);
    	jLpersonal.setText(fechas.fechaHoy);
    }
    
    private void actualizarFecha(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
    	if(evt.getSource() == jBhoy0){
    		jLfechaRegistrada.setText(jLhoy0.getText());
    		reseteaColorBotones();
    		jBhoy0.setBackground(Color.green);
    	}
    	
    	if(evt.getSource() == jBhoy1){
    		jLfechaRegistrada.setText(jLhoy1.getText());
    		reseteaColorBotones();
    		jBhoy1.setBackground(Color.green);
    	}
    	
    	if(evt.getSource() == jBhoy2){
    		jLfechaRegistrada.setText(jLhoy2.getText());
    		reseteaColorBotones();
    		jBhoy2.setBackground(Color.green);
    	}
    	
    	if(evt.getSource() == jBhoy3){
    		jLfechaRegistrada.setText(jLhoy3.getText());
    		reseteaColorBotones();
    		jBhoy3.setBackground(Color.green);
    	}
    	
    	if(evt.getSource() == jBpersonal){
    		
    		System.out.println("Clicando boton personal");
    		
    		jLpersonal.setText(jLfechaRegistrada.getText());
    		reseteaColorBotones();
    		jBpersonal.setBackground(Color.green);
    	}
    }                                      

    public String getFechaActiva(){
    	String fecha = "";
    	if(jBpersonal.getBackground() == Color.green){
    		System.out.println("Color seleccionado... personal" + jBpersonal.getBackground());
    		fecha = jLpersonal.getText();
    	}
    	else if(jBhoy1.getBackground() == Color.green){
    		System.out.println("Color seleccionado... hoy1" + jBpersonal.getBackground().toString());
    		fecha = jLhoy1.getText();
    	}
    	else if(jBhoy2.getBackground() == Color.green){
    		System.out.println("Color seleccionado... hoy2" + jBpersonal.getBackground().toString());
    		fecha = jLhoy2.getText();
    	}
    	else if(jBhoy3.getBackground() == Color.green){
    		System.out.println("Color seleccionado... hoy3" + jBpersonal.getBackground().toString());
    		fecha = jLhoy3.getText();
    	}
    	else {
    		System.out.println("Color seleccionado... hoy" + jBpersonal.getBackground().toString());
    		fecha = jLhoy0.getText();
    	}
    	System.out.println(fecha);
    	
    	return fecha;
    }
    
    private void reseteaColorBotones(){
    	jBhoy0.setBackground(Color.lightGray);
    	jBhoy1.setBackground(Color.lightGray);
    	jBhoy2.setBackground(Color.lightGray);
    	jBhoy3.setBackground(Color.lightGray);
    	jBpersonal.setBackground(Color.lightGray);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaFechas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaFechas().setVisible(true);

            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton jBEnter;
    private javax.swing.JButton jBhoy1;
    private javax.swing.JButton jBhoy2;
    private javax.swing.JButton jBhoy3;
    private javax.swing.JButton jBpersonal;
    public javax.swing.JLabel jLfechaRegistrada;
    private javax.swing.JLabel jLhoy1;
    private javax.swing.JLabel jLhoy2;
    private javax.swing.JLabel jLhoy3;
    private javax.swing.JLabel jLpersonal;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    public javax.swing.JTextField jTextField1;
    // End of variables declaration                   
}

